### PR TITLE
feat: enhance `Language.fromCode()` method with fallback logic to match the language code and the region separately in compound codes 

### PR DESCRIPTION
**Pull request by mikekosulin**
This feature augments the handling of language codes, providing robust support especially for codes in the BCP 47 format (`en-US`/`en_US`), thereby improving overall functionality.

The original functionality remains intact and operational as before.

In the absence of an exact match (which would be [caught by `orElse` with `Language.xx`](https://github.com/moazelsawaf/dash_flags/pull/4/commits/e1a1cc0da4616fe157b5c0c2bdcffcf7b343d655#diff-505261888349aea92dc2f1b0055fe5dd55be4b6def5035e5758e206aa358ece3R481)), the feature will attempt to find a match by dissecting the language code and separately matching each part (specifically in the order of last part followed by the first part). If no match is found even then, it defaults to `Language.xx`.

### CODE REVIEW

**Comment by moazelsawaf** [comment]
I really like this, but why are you reversing the language code after splitting it down? With that reversal, you will be matching the region code first, and the language code second. This is wrong because the priority should be given to the language code, not the region.

**Comment by mikekosulin** [comment]
I guess you're right regarding this case. I've been using this package to display languages for speech recognition, where regional distinction is important.

Perhaps we could add an option `prioritizeRegion: false`. This would allow users to adjust based on their requirements.

**Comment by moazelsawaf** [comment]
I understand your use case, but I think we have to keep the package as convenient as possible. So, matching the code without reverse would keep the result as expected. ✅

For your last commit, I can see that you are agreeing with me about removing the reversal logic. ✅

For the rest of the changes, I have inspected them and I will work on them as soon as possible. Inshallah. 🙏🏻

**Comment by moazelsawaf** [comment]
Thank you @mikekosulin so much for your contribution 🙏🏻💙

I have applied some refactor and removed some of the unrelated changes from the PR.

I am looking for other contributions from you 💙
Have a nice day! 😊

**Pull request merged**
